#!bin/sh
{
while true $a in $='a'
do
menu
clear
echo "=================================="
echo "DeFi Minds Firewall Manager"
echo " nc) Netcat Listen"
echo " a) Chain Manager"
echo " b) Delet All Preset maked"
echo "----------------------------------"
echo " sysctl) Insert Custom sysctl.conf"
echo " wipe) Wipe All FW Rules"
echo " q) quit"
echo "=================================="
read a
 case $a in
	nc)
	 echo "Insert the protol to listen the port, Ex: tcp" && read ncproto
	 echo "Insert the port to listen" && read ncport
	 if [ $ncproto=="tcp" ];
	 then
	  if [ $ncport=<"1024"];
	  then
	   sudo nc -l $ncport
	  else
	   nc -l $ncport
	  fi
	 else
	  if [ $ncport=<"1024"];
	  then
	   sudo nc -u -l $ncport
	  else
	   nc -u -l $ncport
	  fi
	 fi
         echo;;

	a)
	 clear
	 {
	 while true $b in $='b'
	 do
	  echo "====================="
	 echo " 1) ALLOW/DROP IP/PORT"
	 echo " 2) ALLOW/DROP ALL"
	 echo " 3) Del ALL Rules"
	 echo "======================"
	  read b
	   case $b in
		1)
		 echo "Insert Protocol, Ex: tcp" && read protocol
		 echo "Insert Source IP Local, Ex: 192.168.1.10 or  127.0.0.1 or 192.168.1.0/24 <--> 192.168.1.255" && read sourceip
		 echo "Insert Destination IP External, Ex: 1.1.1.1 or range Ex: 1.1.1.0/24 <--> 1.1.1.255" && read externalip
	         echo "Insert Desination Port External, Ex: 80 or you need block all ports insert the text: all" && read destport
	 	 echo "Insert Chain, Ex: INPUT or FORWARD or OUTPUT" && read chain
	  	 echo "Insert Policy, Ex: DROP or ALLOW" && read policy
		if [ $destport=="all" ];
		then
		 destport="01:65535"
		 cmd=sudo iptables -I $chain -p $protocol -s $sourceip -d $externalip --dport $destport -j $policy
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .fwlog
	  	 sudo iptables-save
		else
		 cmd=sudo iptables -I $chain -p $protocol -s $sourceip -d $externalip --dport $destport -j $policy
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .fwlog
		 sudo iptables-save
		fi
		echo;;
		2)
	 	 echo "Insert Chain, Ex: INPUT or FORWARD or OUTPUT" && read chain
	  	 echo "Insert Policy, Ex: DROP" && read policy
		 sudo iptables -P $chain $policy && sudo iptables -I $chain -j $policy
	  	 sudo iptables-save
		echo;;
		3)
		 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.fwlog -i
		 sudo sh /home/$USER/.fwmanager/.fwlog
		 sudo rm -r /home/$USER/.fwmanager/.fwlog
		echo;;
	 esac
	 done
	 }
         echo;;

	c)
	 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.fwlog -i && sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.fwlog -i
	 sudo sh /home/$USER/.fwmanager/.fwlog && sudo sh /home/$USER/.fwmanager/.fwlog
	 sudo rm -r /home/$USER/.fwmanager/.fwlog &&  sudo rm -r /home/$USER/.fwmanager/.fwlog
         echo;;

	q)
         exit;;

	sysctl)
	 echo " Downloading the custom file to replace in /etc/sysctl.conf  ...."
	 sudo mv sysctl.conf /etc/sysctl.conf && sudo sysctl -p
         echo;;

	wipe)
	 sudo iptables -F && sudo iptables -X && sudo iptables -Z
	 sudo iptables -L
         echo;;
esac
done
menu
}
