#!bin/sh
{
while true $a in $='a'
do
menu
clear
echo "=================================="
echo "DeFi Minds Firewall Manager"
echo " nc) Netcat Listen"
echo " a) Chain Manager"
echo " b) Delet All Preset maked"
echo "----------------------------------"
echo "       VULNERABILITIES FIX"
echo " 1) TCP SACK PANIC"
echo "----------------------------------"
echo " sysctl) Insert Custom sysctl.conf"
echo " wipe) Wipe All FW Rules"
echo " q) quit"
echo "=================================="
read a
 case $a in
	nc)
	 echo "Insert the protol to listen the port, Ex: tcp" && read ncproto
	 echo "Insert the port to listen" && read ncport
	 if [ $ncproto=="tcp" ]; then
	  if [ $ncport=<"1024"]; then
	   sudo nc -l $ncport
	  else
	   nc -l $ncport
	  fi
	 else
	  if [ $ncport=<"1024"]; then
	   sudo nc -u -l $ncport
	  else
	   nc -u -l $ncport
	  fi
	 fi
         echo;;

	a)
	 clear
	 {
	 while true $b in $='b'
	 do
	  echo "====================="
	 echo " 1) ALLOW/DROP IP/PORT"
	 echo " 2) ALLOW/DROP ALL"
	 echo " 3) Del ALL Rules"
	 echo "======================"
	  read b
	   case $b in
		1)
		 echo "Insert Protocol, Ex: tcp" && read protocol
		 echo "Insert Source IP Local, Ex: 192.168.1.10 or  127.0.0.1 or 192.168.1.0/24 <--> 192.168.1.255" && read sourceip
		 echo "Insert Destination IP External, Ex: 1.1.1.1 or range Ex: 1.1.1.0/24 <--> 1.1.1.255" && read externalip
	         echo "Insert Desination Port External, Ex: 80 or you need block all ports insert the text: all" && read destport
	 	 echo "Insert Chain, Ex: INPUT or FORWARD or OUTPUT" && read chain
	  	 echo "Insert Policy, Ex: DROP or ALLOW" && read policy
		if [ $destport=="all" ];
		then
		 destport="01:65535"
		 cmd=sudo iptables -I $chain -p $protocol -s $sourceip -d $externalip --dport $destport -j $policy
	  	 mkdir .log/ && echo $cmd >> .ilog
	  	 sudo iptables-save
		else
		 cmd=sudo iptables -I $chain -p $protocol -s $sourceip -d $externalip --dport $destport -j $policy
	  	 mkdir .log/ && echo $cmd >> .ilog
		 sudo iptables-save
		fi
		echo;;
		2)
	 	 echo "Insert Chain, Ex: INPUT or FORWARD or OUTPUT" && read chain
	  	 echo "Insert Policy, Ex: DROP" && read policy
		 sudo iptables -P $chain $policy && sudo iptables -I $chain -j $policy
	  	 sudo iptables-save
		echo;;
		3)
		 sed -i 's/-I/-D/g' ./.log/.ilog -i
		 sudo sh ./.log/.ilog
		 sudo rm -r ./.log/.ilog
		echo;;
	 esac
	 done
	 }
         echo;;

	b)
	 clear
	 {
	 while true $b in $='b'
	 do
	 echo "================================"
	 echo " 1) Block IP/PORT | 2) Block ALL"
	 echo " 3) Del ALL Rules"
	 echo "================================"
	  read b
	   case $b in
		1)
		 echo "Insert Protocol, Ex: tcp" && read protocol
		 echo "Insert Source IP Local, Ex: 192.168.1.10 or  127.0.0.1 or 192.168.1.0/24 <--> 192.168.1.255" && read sourceip
		 echo "Insert Destination IP External, Ex: 1.1.1.1 or range Ex: 1.1.1.0/24 <--> 1.1.1.255" && read externalip
	         echo "Insert Desination Port External, Ex: 80 or you need block all ports insert the text: all" && read destport
		if [ $destport=="all" ];
		then
		 destport="01:65535"
		 cmd=sudo iptables -I OUTPUT -p $protocol -s $sourceip -d $externalip --dport $destport -j DROP
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .olog
		else
		 cmd=sudo iptables -I OUTPUT -p $protocol -s $sourceip -d $externalip --dport $destport -j DROP
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .olog
		fi
		echo;;
		2)
		 sudo iptables -P OUTPUT DROP && sudo iptables -I OUTPUT -j DROP
		echo;;
		3)
		 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.olog -i
		 sudo sh /home/$USER/.fwmanager/.olog
		 sudo rm -r /home/$USER/.fwmanager/.olog
		echo;;
	 esac
	 done
	 }
         echo;;

	c)
	 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.ilog -i && sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.olog -i
	 sudo sh /home/$USER/.fwmanager/.ilog && sudo sh /home/$USER/.fwmanager/.olog
	 sudo rm -r /home/$USER/.fwmanager/.ilog &&  sudo rm -r /home/$USER/.fwmanager/.olog
         echo;;

	q)
         exit;;

	sysctl)
	 echo " Downloading the custom file to replace in /etc/sysctl.conf  ...."
	 sudo mv sysctl.conf /etc/sysctl.conf && sudo sysctl -p && sudo sysctl -w net.ipv4.route.flush=1
         echo;;

	wipe)
	 sudo iptables -F && sudo iptables -X && sudo iptables -Z
	 sudo iptables -L
         echo;;
1)
 sudo iptables -I INPUT -p tcp --tcp-flags SYN SYN -m tcpmss --mss 1:500 -j DROP
 sudo ip6tables -I INPUT -p tcp --tcp-flags SYN SYN -m tcpmss --mss 1:500 -j DROP
 sudo iptables -nL -v && sudo ip6tables -nL -v
sleep 6
echo;;

esac
done
menu
}
