#!bin/sh
{
while true $a in $='a'
do
menu
clear

echo "============================="
echo "DeFi Minds Firewall Manager"
echo " nc) Netcat Listen"
echo " a) Block INPUT"
echo " b) Block OUTPUT"
echo " c) Delet All"
echo " ct) Contacts"
echo " q) quit"
echo "========================="
read a
 case $a in
	nc)
	 echo "Insert the protol to listen the port, Ex: tcp" && read ncproto
	 echo "Insert the port to listen" && read ncport
	 if [ $ncproto=="tcp" ];
	 then
	  if [ $ncport=<"1024"];
	  then
	   sudo nc -l $ncport
	  else
	   nc -l $ncport
	  fi
	 else
	  if [ $ncport=<"1024"];
	  then
	   sudo nc -u -l $ncport
	  else
	   nc -u -l $ncport
	  fi
	 fi
         echo;;

	a)
	 clear
	 {
	 while true $b in $='b'
	 do
	 menu
	 echo "================="
	 echo " 1) Block IP/PORT"
	 echo " 2) Block ALL"
	 echo " 3) Del ALL Rules"
	 echo "================="
	  read b
	   case $b in
		1)
		 echo "Insert Protocol, Ex: tcp" && read protocol
		 echo "Insert Source IP Local, Ex: 192.168.1.10 or  127.0.0.1 or 192.168.1.0/24 <--> 192.168.1.255" && read sourceip
		 echo "Insert Destination IP External, Ex: 1.1.1.1 or range Ex: 1.1.1.0/24 <--> 1.1.1.255" && read externalip
	         echo "Insert Desination Port External, Ex: 80 or you need block all ports insert the text: all" && read destport
		if [ $destport=="all" ];
		then
		 destport="01:65535"
		 cmd=sudo iptables -I INPUT -p $protocol -s $sourceip -d $externalip --dport $destport -j DROP
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .ilog
		else
		 cmd=sudo iptables -I INPUT -p $protocol -s $sourceip -d $externalip --dport $destport -j DROP
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .ilog
		fi
		echo;;
		2)
		 sudo iptables -P INPUT DROP && sudo iptables -I INPUT -j DROP
		echo;;
		3)
		 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.ilog -i
		 sudo sh /home/$USER/.fwmanager/.ilog
		 sudo rm -r /home/$USER/.fwmanager/.ilog
		echo;;
	 esac
	 done
         menu
	 }
         echo;;

	b)
	 clear
	 {
	 while true $b in $='b'
	 do
	 menu
	 echo "================="
	 echo " 1) Block IP/PORT"
	 echo " 2) Block ALL"
	 echo " 3) Del ALL Rules"
	 echo "================="
	  read b
	   case $b in
		1)
		 echo "Insert Protocol, Ex: tcp" && read protocol
		 echo "Insert Source IP Local, Ex: 192.168.1.10 or  127.0.0.1 or 192.168.1.0/24 <--> 192.168.1.255" && read sourceip
		 echo "Insert Destination IP External, Ex: 1.1.1.1 or range Ex: 1.1.1.0/24 <--> 1.1.1.255" && read externalip
	         echo "Insert Desination Port External, Ex: 80 or you need block all ports insert the text: all" && read destport
		if [ $destport=="all" ];
		then
		 destport="01:65535"
		 cmd=sudo iptables -I OUTPUT -p $protocol -s $sourceip -d $externalip --dport $destport -j DROP
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .olog
		else
		 cmd=sudo iptables -I OUTPUT -p $protocol -s $sourceip -d $externalip --dport $destport -j DROP
	  	 mkdir /home/$USER/.fwmanager/ && echo $cmd >> .olog
		fi
		echo;;
		2)
		 sudo iptables -P OUTPUT DROP && sudo iptables -I OUTPUT -j DROP
		echo;;
		3)
		 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.olog -i
		 sudo sh /home/$USER/.fwmanager/.olog
		 sudo rm -r /home/$USER/.fwmanager/.olog
		echo;;
	 esac
	 done
         menu
	 }
         echo;;

	c)
	 sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.ilog -i && sed -i 's/-I/-D/g' /home/$USER/.fwmanager/.olog -i
	 sudo sh /home/$USER/.fwmanager/.ilog && sudo sh /home/$USER/.fwmanager/.olog
	 sudo rm -r /home/$USER/.fwmanager/.ilog &&  sudo rm -r /home/$USER/.fwmanager/.olog
         echo;;


	ct)
	  echo "DeFi Minds contacts at now is these;"
	  echo "Twitter Project: @defiminds| email: defiminds@onionmail.org"
	  echo "Buy me a coffe if you think can the addresses is these;"
	  echo "Bitcoin: 1DAUErsj85tKgkhBBr5Exj8oEk5fE3sBiy"
	  echo "Stacks: SP22RY83R4XBX26K3SK5SX5Z6PQSE3ZSXRT5XRVZF"
	  echo "Ethereum: 0x0987A758c3f9a1d189bd14bEece21Fd61bBC5755"
	  sleep 7
	  echo;;

	q)
         exit;;
esac
done
menu
}
