#!bin/sh
install_browsers(){
install_browsrs(){
clear
echo "What browser your accept install?"
echo "1) Waterfox 2) Librewolf | 3) Brave | 4) Firefox"
echo "q) Quit."
read a
echo "Your choiced $a"
if [ $a=="q" ]; then
exit
elif [ $a=="1" ]; then
sudo mkdir /home/$USER/browser/ && wget https://cdn1.waterfox.net/waterfox/releases/latest/linux && tar -xf linux && cd /home/$USER/browser/waterfox/
echo "You accept open the browser now? | y/n"
read acpb
if [ $acpb=="y"]; then
 xfce4-terminal -x ./waterfox
else
 echo "Browser installed!" && sleep 3
fi
elif [ $a=="2" ]; then
distro=$(if echo " bullseye focal impish jammy uma una vanessa" | grep -q " $(lsb_release -sc) "; then echo $(lsb_release -sc); else echo focal; fi)
wget -O- https://deb.librewolf.net/keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/librewolf.gpg
sudo tee /etc/apt/sources.list.d/librewolf.sources << EOF > /dev/null
Types: deb
URIs: https://deb.librewolf.net
Suites: $distro
Components: main
Architectures: amd64
Signed-By: /usr/share/keyrings/librewolf.gpg
EOF
sudo apt update && sudo apt install librewolf -y
elif [ $a=="3" ]; then
echo "In next updates.."
elif [ $a=="4" ]; then
sudo apt -y update && sudo apt -y install firefox
fi
echo;;
}
# Ask user for input
read -p "Do you want to install one Browser? (y/n) " choice
# Check user input
if [[ "$choice" == [yY] ]]; then
  install_browsrs
else
  echo "Browsers installation canceled by user"
fi
}
install_browsers
